### ISSUE TITLE
qemu-system-x86_64: -nic: invalid option

### ISSUE THREAD

**Issue by samannazz** [rauc/rauc#1024]
I have follow the all step and after running the sudo ./qemu-test. i am getting this error

qemu-system-x86_64: -nic: invalid option

![Screenshot from 2022-12-20 19-59-26](https://user-images.githubusercontent.com/89451747/208702026-1d1783a0-16b1-4625-aa51-b035374228c0.png)

where i have done wrong.

**Comment by ejoerns** [comment]
On which host system do you test this?

The `-nic` option should be provided by your qemu implementation.

Also, note that the purpose of the qemu setup is to allow running test as non-root.

**Comment by samannazz** [comment]
i am running ubuntu 18.04
and this is the some part of my qemu-test file

![Screenshot from 2022-12-20 21-01-52](https://user-images.githubusercontent.com/89451747/208711359-5e90f905-f3da-4aef-97a9-7c84e9616601.png)

**Comment by ejoerns** [comment]
Ubuntu 18.04 comes with QEmu v2.11

https://packages.ubuntu.com/bionic/qemu-system-x86

Please consider using a recent distro.

**Comment by ejoerns** [comment]
For others coming accross this issue:

Alternatives are to use *Ubuntu* LTS 20.04 or 22.04, to use *Debian* buster or bullseye, or to use a container of these or, alternatively, the RAUC testing container http://ghcr.io/rauc/rauc/rauc-ci:latest
