### ISSUE TITLE
Segfault when trying to encrypt plain bundles

### ISSUE THREAD

**Issue by fhars** [rauc/rauc#1054]
This line tries to print a helpful error message in that case:

https://github.com/rauc/rauc/blob/d700dba36c0570d0caf8e10a698713aa00b2457b/src/bundle.c#L1240

but when the bundle is in plain format, the signature type is detached, and the `bundle->manifest` pointer is never changed from its initial NULL value.

**Comment by fhars** [comment]
The pointer is currently set as a side effect of check_bundle(), but only for bundles that don't have a detached signature.

**Comment by ejoerns** [comment]
@fhars confirmed. Good catch!

We should check for `bundle->manifest` being NULL in the condition first I guess.

Would you like to make a PR?
