### ISSUE TITLE
RAUC does not verify checksums present in the manifest file

### ISSUE THREAD

**Issue by zyga** [rauc/rauc#1055]
**Describe the bug**

Since a87a227add1147186bec124b7d409325ebc24321 the function `verify_checksum` is unused. This makes sense for verity bundles but seems premature for plain bundles.

**Background information**

This applies to RAUC since October 8th 2020

**To Reproduce**

Use `git grep verify_checksum` and observe that it is only called from test logic.

**Expected behavior**

RAUC should continue to verify checksums for plain bundles.

**Logs**

N/A

**Additional context**

N/A

**Comment by jluebbe** [comment]
Plain bundles are signed and authenticated as well (using a detached CMS signature). The checksums currently only used to detect identical source images on the target.

Verifying the checksum during installation would be redundant and waste time during installation.
