### ISSUE TITLE
RAUC service does not start on Debian bullseye when built from source

### ISSUE THREAD

**Issue by martin-petzold** [rauc/rauc#1135]
**Describe the bug**

RAUC service does not start.

**Background information**

I have a Debian bullseye (with more recent systemd 252.5 from bullseye-backports). Kernel 5.10.

Tested RAUC 1.9 and HEAD

**To Reproduce**

1. Build and install RAUC as described in the documentation
2. Reboot system
3. Start RAUC service (`sudo systemctl start rauc.service`) OR enable it before reboot
4. Check service (`sudo systemctl status rauc.service`)
 
**Expected behavior**

RAUC service should run.

**Logs**

```
$ sudo systemctl status rauc.service
× rauc.service - RAUC Update Service
     Loaded: loaded (/lib/systemd/system/rauc.service; static)
     Active: failed (Result: exit-code) since Fri 2023-05-19 11:50:52 CEST; 3s ago
       Docs: https://rauc.readthedocs.io
    Process: 530 ExecStart=/usr/local/bin/rauc --mount=/run/rauc service (code=exited, status=1/FAILURE)
   Main PID: 530 (code=exited, status=1/FAILURE)
        CPU: 66ms

Mai 19 11:50:52 tavla systemd[1]: Starting rauc.service - RAUC Update Service...
Mai 19 11:50:52 tavla rauc[530]: Using central status file /var/lib/rauc/central.raucs
Mai 19 11:50:52 tavla rauc[530]: Failed to obtain name de.pengutronix.rauc on system bus
Mai 19 11:50:52 tavla systemd[1]: rauc.service: Main process exited, code=exited, status=1/FAILURE
Mai 19 11:50:52 tavla systemd[1]: rauc.service: Failed with result 'exit-code'.
Mai 19 11:50:52 tavla systemd[1]: Failed to start rauc.service - RAUC Update Service.
```

However, there is also no '/var/lib/rauc/central.raucs' state file, maybe a problem:

```
$ ls -l /var/lib/rauc/
insgesamt 0
```

**Additional context**

It may be a little more specific Debian bullseye setup. However, IMHO it seems to be something more basic related to dbus.

**Comment by martin-petzold** [comment]
I used `sudo meson install` and not `make install` as described in the documentation. A problem?

**Comment by jluebbe** [comment]
You're likely missing the DBus configuration. There are already Debian packages for RAUC. See:
https://salsa.debian.org/debian/rauc/-/tree/debian/master/debian
https://tracker.debian.org/pkg/rauc

If you want to build custom versions, you should probably build on the official packages.

**Comment by martin-petzold** [comment]
I need streaming installation and this is not supported by rauc package 1.5.1 in Debian bullseye main repository. I would like to use most recent version if possible. meson installed some dbus configurations:

```
$ sudo meson install
ninja: Entering directory `.'
[1/1] Generating version.h with a custom command
Installing rauc-installer-generated.h to /usr/local/include
Installing rauc to /usr/local/bin
Installing /home/tavla/rauc/src/de.pengutronix.rauc.Installer.xml to /usr/share/dbus-1/interfaces
Installing /home/tavla/rauc/rauc.1 to /usr/local/share/man
Installing /home/tavla/rauc/build/data/rauc.service to /lib/systemd/system
Installing /home/tavla/rauc/build/data/de.pengutronix.rauc.service to /usr/share/dbus-1/system-services
Installing /home/tavla/rauc/build/data/rauc-service.sh to /usr/local/libexec
Installing /home/tavla/rauc/build/data/de.pengutronix.rauc.conf to /usr/local/share/dbus-1/system.d
```

**Comment by martin-petzold** [comment]
RAUC 1.8 package from Debian bookworm does not contain any service files, only the binary and some documentation: https://packages.debian.org/bookworm/arm64/rauc/filelist

Also the control files do not install or configure any service:

```
Package: rauc
Version: 1.8-2
Architecture: arm64
Maintainer: Uwe Kleine-König <ukleinek@debian.org>
Installed-Size: 425
Depends: libc6 (>= 2.34), libcurl3-gnutls (>= 7.16.2), libfdisk1 (>= 2.31.1), libglib2.0-0 (>= 2.67.1), libjson-glib-1.0-0 (>= 1.5.2), libssl3 (>= 3.0.0), dbus, systemd
Suggests: casync, cryptsetup-bin, dosfstools, e2fsprogs, efibootmgr, grub-common, mtd-utils, squashfs-tools, u-boot-tools
Section: admin
Priority: optional
Homepage: https://github.com/rauc/rauc
Description: Robust Auto-Update Controller - binary
 Safe and secure software updates for embedded Linux
 .
 RAUC controls the update process on embedded Linux systems. It is both a target
 application that runs as an update client and a host/target tool that allows
 you to create, inspect and modify installation artifacts.
 .
 This package provides the rauc binary.
```

It seems this package is only useful for build environment.

IMHO if I build RAUC from source it would be good if it runs on the most recent Debian release.

However, maybe I did something wrong. I know well around systemd and services as well as the basic dbus protocol, but the dbus configuration within systemd is not that common to me.

**Comment by martin-petzold** [comment]
I removed all installed files except of 'rauc' and 'de.pengutronix.rauc.conf'. I moved these two files to:

/usr/bin/rauc
/usr/share/dbus-1/system.d/de.pengutronix.rauc.conf

These seem to be the only files required next to '/usr/lib/systemd/system/rauc.service'. The other files make thinks worse!

Now the service starts and 'sudo rauc status' is working as expected.

IMHO these files should not be installed in 'local' directory, but in default location ('/usr/bin', 'usr/share' etc.). This location is even written in the existing service configuration file: https://github.com/rauc/rauc/blob/master/data/de.pengutronix.rauc.conf. Thus, we have a bug here.

Also I think a lot of things are mixed-up with those files. Especially automatic dbus service start on request and systemd service-based startup. For me it looks very unclean. I am using so many tools, and all of them work on a basic Debian platform.

IMHO this tool should be separated into a daemon executable 'raucd' (the service) and a control executable 'raucctl'.  I have seen several issues here related to such problems and also general miss-understanding about the tool to be used on build and host machine (maybe a feature request should be opened for this).

**Comment by martin-petzold** [comment]
Opened two feature requests: https://github.com/rauc/rauc/issues/1137 and https://github.com/rauc/rauc/issues/1138

Closed this issue, because it is basically solved / explainable. However, the documentation should be enhanced too!

**Comment by ejoerns** [comment]
> It seems this package is only useful for build environment.
> 
> IMHO if I build RAUC from source it would be good if it runs on the most recent Debian release.

FTR: As mentioned in #1137, the Debian package is actually for host usage only. There is [rauc-service](https://packages.debian.org/bookworm/rauc-service) for the required additional target configuration files.

**Comment by ejoerns** [comment]
> I removed all installed files except of 'rauc' and 'de.pengutronix.rauc.conf'. I moved these two files to:
> 
> /usr/bin/rauc /usr/share/dbus-1/system.d/de.pengutronix.rauc.conf
> 
> These seem to be the only files required next to '/usr/lib/systemd/system/rauc.service'. The other files make thinks worse!

Where did you see things getting worse? The purpose of the other files is:

* `de.pengutronix.rauc.Installer.xml`: XML D-Bus interface description. Probably not required on the running system since it is used for generating bindings at build time
* `rauc.1`: The rauc man page. Good to have `man rauc` but not strictly required.
* `de.pengutronix.rauc.service`: The D-Bus service file. Required for D-bus activation of RAUC. Should not break things on a well-configured system. It either activates RAUC via systems service (if available) or via SysVinit wrapper-script
* `rauc-service.sh`: SysVinit wrapper script to set PATH. Not required for systemd-enabled systems.

None of these should break anything.

> Now the service starts and 'sudo rauc status' is working as expected.

Sould not require sudo I guess.

> IMHO these files should not be installed in 'local' directory, but in default location ('/usr/bin', 'usr/share' etc.). This location is even written in the existing service configuration file: https://github.com/rauc/rauc/blob/master/data/de.pengutronix.rauc.conf. Thus, we have a bug here.

`/usr/local/` is the default prefix of meson. You may probably want to configure it with `--prefix=/usr` instead?

I cannot see any location configured in `de.pengutronix.rauc.conf` that has something to do with the paths. Could you explain where you see a bug?

> Also I think a lot of things are mixed-up with those files. Especially automatic dbus service start on request and systemd service-based startup. For me it looks very unclean. I am using so many tools, and all of them work on a basic Debian platform.

Can you clarify what is unclean? If the service already started, it does not need to be activated by D-Bus. I don't see an issue here.

> IMHO this tool should be separated into a daemon executable 'raucd' (the service) and a control executable 'raucctl'. I have seen several issues here related to such problems and also general miss-understanding about the tool to be used on build and host machine (maybe a feature request should be opened for this).

That is to be discussed in #1138 then.

**Comment by martin-petzold** [comment]
> > Also I think a lot of things are mixed-up with those files. Especially automatic dbus service start on request and systemd service-based startup. For me it looks very unclean. I am using so many tools, and all of them work on a basic Debian platform.
> 
> Can you clarify what is unclean? If the service already started, it does not need to be activated by D-Bus. I don't see an issue here.
> 

If I understand right, these d-bus configuration files will somehow start the rauc service?! It is confusing to read `Exec=/usr/share/rauc/rauc-service.sh` and `SystemdService=rauc.service` in one service file. I would always be worried it would be started twice. However, this could be completely correct like this.

On my Debian platform I usually have service startup and dependencies configured in the systemd service files (would be in `/usr/lib/systemd/system/rauc.service`). Currently this service does not have an `install` section (i have added 'WantedBy=default.target' for mine). On common systemd platforms this service would be enabled on firstboot  during preset handling. So, it would be enabled, but not started. Then it seems it would be started by these d-bus configuration files, right?

RAUC is setup as a d-bus only service, but I actually thought it is a daemon. But maybe I am wrong, because this tool does not really do anything in background, you only want to provide the d-bus frontend?

For example BlueZ as a very common tool has a a `bluetooth.service` with install section starting `bluetoothd` and then there also seems to be a `/usr/share/dbus-1/system-services/org.bluez.service`. And the systemd service is located in `/etc/systemd/system/dbus-org.bluez.service`.

```
$ cat /usr/share/dbus-1/system-services/org.bluez.service
[D-BUS Service]
Name=org.bluez
Exec=/bin/false
User=root
SystemdService=dbus-org.bluez.service
```

I think I have not really understood what is going on with all these d-bus-related systemd services. I will try to understand this better.

**Comment by martin-petzold** [comment]
> > IMHO these files should not be installed in 'local' directory, but in default location ('/usr/bin', 'usr/share' etc.). This location is even written in the existing service configuration file: https://github.com/rauc/rauc/blob/master/data/de.pengutronix.rauc.conf. Thus, we have a bug here.
> 
> `/usr/local/` is the default prefix of meson. You may probably want to configure it with `--prefix=/usr` instead?
> 
> I cannot see any location configured in `de.pengutronix.rauc.conf` that has something to do with the paths. Could you explain where you see a bug?
> 

https://github.com/rauc/rauc/blob/master/data/de.pengutronix.rauc.conf#L6

`It is usually installed to /usr/share/dbus-1/system.d`, but it is (by meson default, as you say) installed in `/usr/local/share/dbus-1/system.d`. So either maybe change the comment or maybe change the documentation adding `--prefix=/usr` to the meson commands, which I have seen in several projects.
