### ISSUE TITLE
RAUC should be separated into a daemon executable 'raucd' (the service) and a control executable 'raucctl'

### ISSUE THREAD

**Issue by martin-petzold** [rauc/rauc#1138]
**Is your feature request related to a problem? Please describe.**

I have seen several issues related to miss-understanding about RAUC to be used on build and host machine. When using Debian as build and host platform it can also be confusing. Because on the embedded platform there is a daemon AND a control use case.

**Describe the solution you'd like**

This tool should be separated into a daemon executable 'raucd' (the service) and a control executable 'raucctl'.

**Comment by martin-petzold** [comment]
Okay, there is already a separate RAUC service package for Debian as mentioned in https://github.com/rauc/rauc/issues/1137: https://packages.debian.org/bookworm/rauc-service

However, I will open a new ticket to add this to the documentation.

**Comment by martin-petzold** [comment]
Also it seems that RAUC is not meant to be a daemon at the moment, rather only a tool with dbus frontend.

**Comment by jluebbe** [comment]
This is incorrect. The `rauc` binary provides both the client and D-Bus service, depending on build-time configuration. Accordingly, the `rauc-service` Debian package provides only the necessary configuration files.

Combining both aspects into a single binary is done done to save some space, which is relevant for resource constrained systems.
