### ISSUE TITLE
Status file writing failed

### ISSUE THREAD

**Issue by mwakaM00n** [rauc/rauc#1154]
**Describe the bug**
We use RAUC in the symetric scheme to update our system. The status file is shared between the two updatable slots (emmc) by using a SD card. Sometimes, at the end of the update process, we face the following issue : 
Installation erroe: Error while writing status file: Failed to create file /media/mmclk2p1/statusfile.X6GB61: readonly filesystem.

**Background information**
We are using RAUC version 1.5.1 with Yocto on dunfell flavor.

**To Reproduce**
Simply start a update process

**Expected behavior**
The status file writing may work properly on the SD card.

**Logs**
During process 
```
[ 3804.695450] FAT-fs (mmcblk2p1): error, fat_free_clusters: deleting FAT entry beyond EOF
[ 3804.703547] FAT-fs (mmcblk2p1): Filesystem has been set read-only
```

**Additional context**

**Comment by ejoerns** [comment]
@mwakaM00n  This looks like an issue between the kernel and your FAT partition.

Is the FAT still usable after a reboot? (Why FAT? is this a boot partition?)
Could you dump your partitioning scheme and maybe `mount` output?

**Comment by mwakaM00n** [comment]
Hi @ejoerns,

The FAT partition is in some cases reusable after a reboot, sometimes a fsck is mandatory to turn it into good state.
FAT FS is use on this SDCARD for data storage purpose.
Mount option for this device is:
` /dev/mmcblk2p1 on /media/mmcblk2p1 type vfat (rw,relatime,gid=6,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)`

fdisk tool shows below output : 
```
Disk /dev/mmcblk2: 14.86 GiB, 15931539456 bytes, 31116288 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x9ffa707e

Device         Boot Start      End  Sectors  Size Id Type
/dev/mmcblk2p1         16 31116287 31116272 14.9G  c W95 FAT32 (LBA)

```

**Comment by ejoerns** [comment]
Ok, so it is the entire SD card used for the status file, got it.

I wonder if only RAUC status file writing fails or if other write access to the card fails, too?
From what I see it does not look like a RAUC-specific issue but with an issue of your SD card.

Another guess would be that the card is somehow not properly mounted (yet) or something similar when attempting to write to it.

The reason it is `ro` after a failure is of course the `error=remount,ro` option.

**Comment by jluebbe** [comment]
Could you attach your `system.conf` and post the eMMC partitioning? I'd like to understand why you store a status file on an SD card.

**Comment by ejoerns** [comment]
@mwakaM00n I guess the question was if it is intentional that you do not store the status on the eMMC which holds the rootfs partitions. Is there no room for adding a (small) shared data partition?

The FAT partitions are used to store the kernel?

**Comment by ejoerns** [comment]
@mwakaM00n Anything new on this? Or do you tink we can close this?

**Comment by mwakaM00n** [comment]
Hi @ejoerns,

We will change the place where statusfile is stored to avoid SD card failure, by creating a common partition between 2 systems, thanks for this suggestion.

Regards

**Comment by ejoerns** [comment]
@mwakaM00n Sounds good! Thank your for the feedback!

If you already change this and use a recent RAUC version, consider using [data-directory](https://rauc.readthedocs.io/en/latest/reference.html#data-directory) instead.
