### ISSUE TITLE
Status doesn't show correct data when both partitions has 0 boots left 

### ISSUE THREAD

**Issue by Paiusco** [rauc/rauc#1202]
**Describe the bug**
Whenever both partitions A and B has 0 boots left, some information gets lost on `rauc status`, like in the following image:
![rauc-a0-b0](https://github.com/rauc/rauc/assets/2374887/491f2fb1-c257-48de-86f5-650069768afb)

**Background information**
Using rauc version 1.9
Built using Yocto kirsktone

**To Reproduce**
1. fw_setenv BOOT_A_LEFT 0
2. fw_setenv BOOT_B_LEFT 0
3. rauc status

**Expected behavior**
Would expect to have a clear overview of what bootloader partition was booted. (instead of `(null) ((null))`)
On `Bootloader Activated: ...`
It should also show which partition is the primary, as it just booted from it.

**Additional context**
I think rauc only considers valid a partition that's bigger than 0, however if we max of tries is 1 or if it failed a few times up until it reached 0, booting from 0 left is also a valid one, until it restarts again before being marked as good.

If we see a possible fix, I can submit a PR.

**Comment by ejoerns** [comment]
@Paiusco I am not sure if I understand the issue correctly.

> Would expect to have a clear overview of what bootloader partition was booted. (instead of (null) ((null)))

The information what bootloader partition is booted is in your above-mentioned log:

    Booted from: rootfs.0 (A)

The information shown in `Activated: ` reflects the boot target that would be booted on the *next* boot. If you disable both, none will be booted (let's exclude possible reset mechanisms in the bootloader here that RAUC cannot know about).

Thus I would assume the information shown in your logs looks quite consistent. Am I wrong?

> I think rauc only considers valid a partition that's bigger than 0, however if we max of tries is 1 or if it failed a few times up until it reached 0, booting from 0 left is also a valid one, until it restarts again before being marked as good.

If no mark-good was executed yet, the next boot will fail because of 0 attempts. If a mark-good was already executed, the information shown in 'Activated: ' should actually say 'good'. Thus the result depends on if you run `rauc status` before or after marking good.

**Comment by Paiusco** [comment]
@ejoerns It was not clear for me that the `bootloader active:` would give me the next boot. Maybe I missed that on the documentation, thank you! (or can it be improved?)

However, I feel it doesn't look nice that the message becomes `(null) ((null))` instead of something a bit clearer like `Unable to find next boot partition`. What do you think?

**Comment by ejoerns** [comment]
> @ejoerns It was not clear for me that the bootloader active: would give me the next boot.

Indirectly. It shows how the bootloader is currently configured. And this determines what will be booted

> Maybe I missed that on the documentation, thank you! (or can it be improved?)

Not sure where but suggestions are always welcome! Also for the user interface.

> However, I feel it doesn't look nice that the message becomes (null) ((null)) instead of something a bit clearer like Unable to find next boot partition. What do you think?

I'd agree that `(null) ((null))` is not the most user-friendly representation. If we see null, we could say:

    Activated: none

The warning emitted in your example already tells the verbose background: 

    Failed getting primary slot: uboot backend: Unable to find primary boot slot

> > If a mark-good was already executed, the information shown in 'Activated: ' should actually say 'good'
>
> That's not the case, right? ...

I actually meant it should say print the activated slot (not 'good') :wink:

**Comment by ejoerns** [comment]
> I'd agree that (null) ((null)) is not the most user-friendly representation. If we see null, we could say:
> Activated: none

I have addressed this in #1239 now to gain a bit of enhancement out of this issue. 

@Paiusco Anything left from your site or could we close the issue then?

**Comment by Paiusco** [comment]
@ejoerns I planned to send a patch, you were faster tho :)
I saw it and it looks good, that's all then. Thanks.

**Comment by ejoerns** [comment]
@Paiusco Oh sorry, I didn't have in mind anymore that you actually promised to make a PR for it.
I bet there are even more options like this in RAUC :wink:

Thanks for your feedback, I will close it then.
