### ISSUE TITLE
Userinterface is not intuitive

### ISSUE THREAD

**Issue by mgrzeschik** [rauc/rauc#14]
When creating a bundle, you have to point to an folder where the
manifest.raucm is available. The filename seems to be fixed. It can
not be changed. You have to suffix the generated bundle with raucb,
otherwise the installer routine will not recognize it as a bundle.

**Comment by gavinschenk** [comment]
I used ipkg/opkg in my last PTXDIST-project and build an update process around ipkg-Repositories. As in your solution we bundled multiple ipk-files to a squashfs and provided one file as update. After having some problems with blacklisting/whitelisting some packages the system runs good. 

What do you think about combining ipgk/opkg and RAUC in future -> opkg-handler for RAUC ...

**Comment by ejoerns** [comment]
Hi, please open a new Issue/request when discussing topics not related to this issue. Thanks!

**Comment by ejoerns** [comment]
Please check #95 and give a short feedback if you find that helpful and sufficient or let us know where we could improve RAUC further concerning this topic (documentation / tooling / warnings).

**Comment by ejoerns** [comment]
Closed due to inactivity. Probably fixed.
