### ISSUE TITLE
Failed to obtain name on system bus despite dbus files installed

### ISSUE THREAD

**Issue by Zylatis** [rauc/rauc#1479]
**Describe the bug**
After following the install steps to get RAUC on a ubuntu target (virtualized), the dbus service fails to start and i cannot install the bundle generated on host.

**Background information**
I am testing out RAUC in a VM (which as far as i can tell should not be an issue?). It compiles and installs with no problems, and puts the dbus service/config files in the correct place. However when trying to install it times out due do the dbus service failing (logs below)

**To Reproduce**
As described above

**Expected behavior**
I expect the service to start and to be able to install a bundle

**Logs**
Install log
![install log](https://github.com/user-attachments/assets/d85171bf-9b44-4ca8-9e2a-d0b7d4ed378d)
Dbus file loc
![dbusfiles](https://github.com/user-attachments/assets/171d3ba7-bf9d-4bca-a3f5-1886787d3706)
Service failure
![failure](https://github.com/user-attachments/assets/3ce2e9eb-db6f-46cc-8f4a-af10317c7c39)
Conf location
![conf](https://github.com/user-attachments/assets/c7f9369c-b88e-4d1e-a9c7-b10d7ce56fcc)
Conf contents
- i don't have a data location because that was listed as optional and the logs above seem to indicate it handles it fine?
![confdetails](https://github.com/user-attachments/assets/d3d2e6b4-da2f-4034-96aa-82d47961f65d)

**Additional context**
I have seen this issue crop up in other contexts but the cause in those cases seemed to be incorrect install/lack of dbus config but i can't see what i'm missing in that regard here. I also saw some discussion of building without the dbus service but i'm unsure of how to do that/if it's appropriate. 

Thanks in advance, happy to provide more info. Looking forward to getting RAUC up and running!

EDIT: (to be fair i don't know this is definitely a bug but that was the closest option)

**Comment by Zylatis** [comment]
Ah, i see it is meant to copy files to `/etc/dbus-1/system/` instead maybe, at least moving from `/usr/share` to there has fixed it. Not sure if this is correct or if i understand what's going on very well though...

**Comment by ejoerns** [comment]
@Zylatis Thanks for reporting. I guess this is caused by dbuspolicydir being `/usr/local/share/dbus-1/system.d` in your install log above. I have checked how this directory is constructed and proposed a fix in #1483.

Would be great if you could test it.
