### ISSUE TITLE
External PKI for signing rauc bundle

### ISSUE THREAD

**Issue by kavithabk** [rauc/rauc#1532]
We plan to use external PKI to sign our RAUC bundle (using verity format)

1.Extract the bundle signature
$ rauc extract-signature --keyring ca.cert.pem bundle.raucb extracted-signature.cms
2. Extract embedded manifest from the verity bundle CMS
$ openssl cms -verify -CAfile ca.cert.pem -out manifest.raucm -inform DER -in extracted-signature.cms
3. Or without trust chain verification
$ openssl cms -verify -noverify -out manifest.raucm -inform DER -in extracted-signature.cms
4.Sign the manifest with your external PKI (for this example, it was made by an openssl command)
$ openssl cms -sign -signer new-signer.cert.pem -CAfile new-ca-cert.pem -inkey new-signer.key.pem -nodetach -in manifest.raucm -outform der -out new-signature.cms
5. Finally replace the bundle signature
$ rauc replace-signature --keyring ca-cert.pem --signing-keyring new-ca-cert.pem bundle.raucb new-signature.cms new-bundle.raucb

We get below error when we run the last step "Signature data is no valid CMS".
I am using a signature in PKCS7 format for our signature, please let me know any pointers what is done wrong , if you have used external PKI for signing .

**Comment by jluebbe** [comment]
Does `openssl cms -verify` work on `new-signature.cms`? If you can publish your signature, please attach it here so that we can take a look.

**Comment by kavithabk** [comment]
openssl cms -verify -CAfile signer_service_RootCA_ECC.pem -inform der -signer out.cms -in new.cms
CMS Verification failure
40D73EDFDB710000:error:1700007F:CMS routines:check_content:no content:../crypto/cms/cms_smime.c:83:



openssl cms -verify -CAfile signer_service_RootCA_ECC.pem -inform der -signer out.cms -in new.cms
CMS Verification failure
40D73EDFDB710000:error:1700007F:CMS routines:check_content:no content:../crypto/cms/cms_smime.c:83:


penssl cms -verify -CAfile signer_service_RootCA_ECC.pem -inform der -signer out.cms -in new.cms
CMS Verification failure
40D73EDFDB710000:error:1700007F:CMS routines:check_content:no content:../crypto/cms/cms_smime.c:83:




NEW




penssl cms -verify -CAfile signer_service_RootCA_ECC.pem -inform der -signer out.cms -in new.cms
CMS Verification failure
40D73EDFDB710000:error:1700007F:CMS routines:check_content:no content:../crypto/cms/cms_smime.c:83:




openssl cms -verify -CAfile signer_service_RootCA_ECC.pem -inform der -signer out.cms -in new.cms
CMS Verification failure
40D73EDFDB710000:error:1700007F:CMS routines:check_content:no content:../crypto/cms/cms_smime.c:83:

Like you said verification fails..
Are these configuration required while  signing ?
 v3_leaf_codesign ]
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer:always
basicConstraints = CA:FALSE
extendedKeyUsage=critical,codeSigning

**Comment by jluebbe** [comment]
> ```
> openssl cms -verify -CAfile signer_service_RootCA_ECC.pem -inform der -signer out.cms -in new.cms
> CMS Verification failure
> 40D73EDFDB710000:error:1700007F:CMS routines:check_content:no content:../crypto/cms/cms_smime.c:83:
> ```
> 
> Like you said verification fails.

As `openssl cms -verify` fails, this is not a RAUC-specific problem.

> Are these configuration required while signing ?
> 
> ```ini
> [v3_leaf_codesign ]
> subjectKeyIdentifier=hash
> authorityKeyIdentifier=keyid:always,issuer:always
> basicConstraints = CA:FALSE
> extendedKeyUsage=critical,codeSigning
> ```

`openssl cms` and RAUC default to the `smimesign` purpose, so either you need to use a PKI matching that or set a different purpose to check for in the RAUC config (see `check-purpose` in https://rauc.readthedocs.io/en/latest/reference.html#keyring-section).

> Should we use PKCS#1 v1.5 or 2.1 (PSS) with RSA?

I think both should work with OpenSSL's CMS implementation, but am not completely sure.

> This is the exact error with RSA
> 
> ./rauc replace-signature --keyring ca.cert.pem --signing-keyring signer_service_RootCA_ECC.pem bundle.raucb new.cms new-bundle.raucb rauc-Message: 11:10:24.481: Reading bundle: bundle.raucb rauc-Message: 11:10:24.486: Verifying bundle signature... rauc-Message: 11:10:24.487: Verified inline signature by 'O = Test Org, CN = Test Org Development-1' 007864695F7E0000:error:1700006B:CMS routines:cms_get_enveloped_type:content type not enveloped data:../crypto/cms/cms_env.c:41: 007864695F7E0000:error:1700006B:CMS routines:cms_get_enveloped_type:content type not enveloped data:../crypto/cms/cms_env.c:41: 007864695F7E0000:error:1700006B:CMS routines:cms_get_enveloped_type:content type not enveloped data:../crypto/cms/cms_env.c:41: rauc-Message: 11:10:24.488: Verifying bundle payload... Reading bundle in 'verity' format rauc-Message: 11:10:24.815: Keyring given, enabling signature verification rauc-Message: 11:10:24.815: Reading bundle: new-bundle.raucb rauc-Message: 11:10:24.816: Verifying bundle signature... 007864695F7E0000:error:1700006B:CMS routines:cms_get_enveloped_type:content type not enveloped data:../crypto/cms/cms_env.c:41: 007864695F7E0000:error:1700006B:CMS routines:cms_get_enveloped_type:content type not enveloped data:../crypto/cms/cms_env.c:41: 007864695F7E0000:error:17000064:CMS routines:cms_signerinfo_verify_cert:certificate verify error:../crypto/cms/cms_smime.c:289:Verify error: unable to get local issuer certificate Failed to replace signature: failed to verify the new bundle: signature verification failed: error:1700006B:CMS routines::content type not enveloped data

You can use `openssl cms -verify -in <file> -inform DER -noverify` to print the contents of the signatures produced by RAUC and by your setup and look for differences.

**Comment by kavithabk** [comment]
eContentType: pkcs7-data (1.2.840.113549.1.7.1)
The manifest is not present in the signature and it has an intermediate certificate (Its an Certificate chain)

**Comment by jluebbe** [comment]
> Do we need to include manifest file in the signature?

If the CMS generated by RAUC has a manifest, you're using the `verity` format, so your new signature must have that as well. See https://rauc.readthedocs.io/en/latest/reference.html#sec-ref-formats.

So far, this doesn't seem to be an issue in RAUC, but in your project-specific integration, so this is not really in scope for community support. You may want to consider commercial support (see https://rauc.io/pages/support.html) if you can't provide more details (such as the signature files).

**Comment by kavithabk** [comment]
thanks a lot for the valuable input

**Comment by jluebbe** [comment]
Please feel free to open a discussion thread at https://github.com/rauc/rauc/discussions if you can provide more information so the community can help with the integration aspects.

Of course, if you find an issue in RAUC itself, please don't hesitate to open a new issue.
