### ISSUE TITLE
unintuitive option `ignore-checksum`

### ISSUE THREAD

**Issue by ukleinek** [rauc/rauc#221]
IMHO the slot option `ignore-checksum` is misnamed. For a piece of software that should write an image somewhere I would expect that adding `ignore-checksum` results in the installation of the image even if the checksum that is part of the image doesn't match. According to [its documentation](http://rauc.readthedocs.io/en/latest/reference.html?highlight=ignore-checksum#slot-slot-class-idx-section) its about skipping installation if the image to install is already installed.

IMHO a better name for this function would be `force-install-same`.

**Comment by jluebbe** [comment]
@jremmet what do you think about renaming this to `force-install-same`?

**Comment by jremmet** [comment]
Agree from user view `force-install-same` is much better

**Comment by ejoerns** [comment]
@ukleinek would you like to send a patch? For backwards-compatibility we must accept both options.

**Comment by ejoerns** [comment]
Anyone who likes to implement this? ;) Or should be close it as unresolved?

**Comment by jluebbe** [comment]
I agree that `force-install-same` is much clearer. `ignore-checksum` needs to stay for compatibility.

**Comment by jremmet** [comment]
I'll look into it.

**Comment by ejoerns** [comment]
This was fixed by #280. Thanks!
