### ISSUE TITLE
How to get log messages output

### ISSUE THREAD

**Issue by hpatriarche** [rauc/rauc#330]
Hi,
I am struggling to get more output message.
I would like to get message from g_message statement. But neither in console output or in /var/log/messages I get any of those log.
What the way to get those log ?

Thanks, Herve.

**Comment by ejoerns** [comment]
@hpatriarche, depends on how you start your service.

If you use the default systemd way, the log will go into systemd journal and you can access it as for every unit using

    journalctl -u rauc

**Comment by hpatriarche** [comment]
Humm, I am with sysvinit
So I do not have journalctl tool

**Comment by ejoerns** [comment]
It really depends on how you start the RAUC service. RAUC simply logs to stdout.
Everything else is up to your service script.

So, how do you start the service? With init script during system startup / D-Bus activation?..
How does it look like?

In general, with sysvinit scripts, one uses something like

    rauc service > /var/log/rauc.log 2>&1

or the `logger` tool.

And, why not using systemd?

**Comment by ejoerns** [comment]
@hpatriarche did that solve your problems?

**Comment by hpatriarche** [comment]
@ejoerns yes, I fixed it. Thanks.

**Comment by ejoerns** [comment]
@hpatriarche Great! Thanks for your answer, thus I can safely close this thread.
