### ISSUE TITLE
Installing bundle from http fails

### ISSUE THREAD

**Issue by FabianKnapp** [rauc/rauc#352]
I tried to install a bundle from a http ressource with

`rauc install http://192.168.2.4/foobar.raucb`

```
rauc-Message: installing http://192.168.2.4/foobar.raucb: installing
rauc-Message: installing http://192.168.2.4/foobar.raucb:   0% Installing
rauc-Message: installing http://192.168.2.4/foobar.raucb:   0% Determining slot states
rauc-Message: installing http://192.168.2.4/foobar.raucb:  20% Determining slot states done.
rauc-Message: installing http://192.168.2.4/foobar.raucb:  20% Checking bundle
rauc-Message: installing http://192.168.2.4/foobar.raucb:  40% Checking bundle failed.
rauc-Message: installing http://192.168.2.4/foobar.raucb: 100% Installing failed.
rauc-Message: installing http://192.168.2.4/foobar.raucb: LastError: Failed to download bundle http://192.168.2.4/foobar.raucb: Transfer failed: Failed writing body (0 != 5792)
```

Installing `http://192.168.2.4/foobar.raucb` failed

/tmp/_download.raucb has always exactly 8MB size but foobar.raucb is 50MB
I think this is a libcurl specific error but dont know how to fix it. Any ideas?

Im using rauc 0.4

**Comment by jluebbe** [comment]
You need to set the max-bundle-download-size in the [system] section of [system.conf](https://rauc.readthedocs.io/en/latest/reference.html?highlight=max-bundle-download-size).

I'd suggest handling the download outside of rauc, in the same custom process which controls when the update is installed. (except when using the experimental casync support).

**Comment by FabianKnapp** [comment]
Thank you!

**Comment by ejoerns** [comment]
@nadhem09 you might want to have a look at https://rauc.readthedocs.io/en/latest/advanced.html#http-streaming

Feel free to open further questions as [Discussions](https://github.com/rauc/rauc/discussions).
