### ISSUE TITLE
rauc/src/bootchooser.c does not use the same default value that is specified in device-tree

### ISSUE THREAD

**Issue by EugenWiens** [rauc/rauc#361]
When the the default values of the state ist changed rauc doesn't use them after an update:

Reset Values to default "bootchooser -a default"
Parameters:
  bootstate.last_chosen: 1 (type: uint32)
  bootstate.system0.priority: 20 (type: uint32)
  bootstate.system0.remaining_attempts: **5** (type: uint32)
  bootstate.system1.priority: 10 (type: uint32)
  bootstate.system1.remaining_attempts: **5** (type: uint32)
  dirty: 0 (type: bool)
  init_from_defaults: 0 (type: bool)
  save_on_shutdown: 1 (type: bool)

After an update the values are set to **3**
bootstate.system0.remaining_attempts=**3**
bootstate.system0.priority=20
bootstate.system1.remaining_attempts=**3**
bootstate.system1.priority=10
bootstate.last_chosen=1

**Comment by ejoerns** [comment]
Hi @EugenWiens, you are right, this is currently hard-coded:

https://github.com/rauc/rauc/blob/master/src/bootchooser.c#L18

The default that barebox bootchooser uses is set in barebox nv variables and RAUC
cannot easily inspect them.

But I agree that the way it is currently implemented is not very convenient for applying custom defaults.
One way could be to make this configurable in system.conf.

Note that we have 2 different defaults, depending on whether we just installed a new image or just execute 'mark-good'.

**Comment by EugenWiens** [comment]
> One way could be to make this configurable in system.conf.
It is not the best way but much better then hard-coding this value.

**Comment by ejoerns** [comment]
@EugenWiens as you know, RAUC development is use-case driven, thus feel free to patch it or choose someone to do so ;)

I also won't be sad about finding a 'better' solution, thus if you have any idea, feel free to discuss.

**Comment by EugenWiens** [comment]
@ejoerns I will try to create an patch on my side.

> I also won't be sad about finding a 'better' solution, thus if you have any idea, feel free to discuss.

Is it possible to read the value from device-tree? like this:
cat /sys/firmware/devicetree/base/state/bootstate/system0/remaining_attempts/default

**Comment by ejoerns** [comment]
FTR: IIRC @jremmet had a similar use-case some time ago as he posted the patches that at least introduced the defines we have today (see #101)

**Comment by EugenWiens** [comment]
@ejoerns sorry for the missing feedback. I created an patch and set the desired values.

**Comment by ejoerns** [comment]
@EugenWiens Ok, this sounds to me like a non-mainlinable solution with fixed values replaced, right?

Then I would close this PR for now, feel free to reopen in case I misunderstood.

**Comment by EugenWiens** [comment]
It is fine for me.

Enrico Jorns <notifications@github.com> schrieb am Mo., 10. Dez. 2018,
17:41:
