### ISSUE TITLE
[QUESTION] How should I use ext2 with RAUC

### ISSUE THREAD

**Issue by manszigher** [rauc/rauc#373]
Hi,

We have an bug currently that prevents us from using ext4 so while working on that issue I am trying to use ext2 instead but I cannot see that it is actually supported when glancing through the code. I have just glanced through the code so I am pretty sure that I am missing something but I cannot figure out what I should supply RAUC to get it to update using our ext2 rootfs. If we look at 

https://github.com/rauc/rauc/blob/0745c7bf6c7828216aad51f47bfe942066abc163/src/update_handler.c#L1312

There is no indication of ext2. The only pair that I could think of is *.img, ext4 but I suspect that RAUC will then format using mkfs.ext4 and not mkfs.ext2. Any help would be appreciated.

BR
Måns Zigher

**Comment by FabianKnapp** [comment]
Hi,

I think it should be no big deal to patch RAUC for ext2 usage:

https://github.com/rauc/rauc/blob/67c516576fb53b3fc7dbdf13a6189ffacc20de17/src/update_handler.c#L389

**Comment by manszigher** [comment]
Sure just wanted to know since in the documentation it states ext2/ext3/ext4 but could not see that that was the case in code. But then I know thanks.

**Comment by manszigher** [comment]
Thanks for the help. Ext2 was a temp fix for us so I am going for squashfs since we would like to have that as our filesystem in the end so I will not put any efforts in the ext2. But I appreciate your help.

**Comment by ejoerns** [comment]
@manszigher You're welcome. This sounds like a plan! Than I will close this.
