### ISSUE TITLE
version handling in git snapshot improvable

### ISSUE THREAD

**Issue by ukleinek** [rauc/rauc#375]
Hello,

if rauc is build e.g. from https://github.com/rauc/rauc/archive/v1.0-rc1-59-g0745c7bf6c78.tar.gz there is no version input for the `git-version-gen` script yielding

    root@$machine:~ rauc --version
    rauc UNKNOWN

Something like `v1.0-rc1` or `v1.0-rc1+` even would be great here.

**Comment by jluebbe** [comment]
The tar archives automatically generated by github do not contain the necessary information. Either build from a git checkout or use a (pre-)release tar archive.

**Comment by ukleinek** [comment]
I just noticed that --fallback doesn't work as intended. The reason is the following in `git-version-gen`:

    [...]if test "x$fallback" = x || git --version >/dev/null 2>&1; then
        v=UNKNOWN
    else
        v=$fallback
    fi

So the fallback is never used if git is properly installed.
