### ISSUE TITLE
Verify error:unable to get local issuer certificate

### ISSUE THREAD

**Issue by sholzmayer** [rauc/rauc#394]
The installation of the self signed raucb file always fails with the following error message: `Verify error:unable to get local issuer certificate`.

The output of `rauc info my-file.raucb` is:
```
rauc-Message: 13:57:57.329: Reading bundle: my-file.raucb
rauc-Message: 13:57:57.401: Verifying bundle... 
signature verification failed: Verify error:unable to get local issuer certificate
```

Any idea what the problem could be? Where is the `local issuer certificate` located?

**Comment by sholzmayer** [comment]
Yeah in the `/etc/rauc/system.conf` is the keyring defined and also present on the system:
```
[keyring]
path=/etc/rauc/keyring.pem
```
Any idea about the `local issuer certificate`? What is it and where is it located at?

**Comment by ejoerns** [comment]
@sholzmayer did you resolve your issue?

**Comment by sholzmayer** [comment]
This solved my problem. Thank you very much!

I used the wrong certificate combination, because the CA also had a root certificate and i got a certificate mismatch.
