### ISSUE TITLE
Failure installing large filesystems on 32bit machines

### ISSUE THREAD

**Issue by fboor** [rauc/rauc#463]
A colleague just ran into a problem installing ext4 images > 2GB on a 32bit machine. I took a look at the code and found this: 
The reason seems to be the use of g_output_stream_splice() in update_handler.c, line 134. The documentation of that function indicates that it supports writing files larger than G_MAXSSIZE (which from what I know is limited by the actual size of size_t) but the returned value does not correspond to the actual size processed any more. As a result the size check fails even if the image was written completely.

**Comment by jluebbe** [comment]
Yes, checking the return value from g_output_stream_splice() (except for errors) is problematic. We could simply drop the check, but I'd prefer to keep some sort of sanity check there.
I think we should use g_seekable_tell() on the instream as GFileInputStream implements GSeekable.

**Comment by ejoerns** [comment]
I've created #503 to address the issue described. Please have a look.
