### ISSUE TITLE
Acknowledge bit in EXT_CSD_PART_CONFIG is reset when flashing eMMC boot partition

### ISSUE THREAD

**Issue by s-michaelsen** [rauc/rauc#481]
When flashing a boot partition of an eMMC device the BOOT_ACK (bit 6) bit in EXT_CSD_PART_CONFIG is reset in function r_emmc_write_bootpart().

I'm not sure if this is really the desired behavior. Maybe it would be good to read current status of this bit and keep it or maybe add an appropriate slot option to set it along with partition number?

Of course it could also be set in a script after bootloader was flashed but since missing of this bit might prevent a proper boot on some systems (e.g. TIs AM57xx processors) it might make the update process more reliable if it gets set along with the partition number.

**Comment by Bastian-Krause** [comment]
Hi,

I agree, we should preserve the `BOOT_ACK` bit when writing the `PARTITION_CONFIG` register.

Could you create a Pull Request for this?

Regards,
Bastian

**Comment by s-michaelsen** [comment]
done ;)

BR,
Stephan
