### ISSUE TITLE
rauc convert should pass on chunk size parameter to casync

### ISSUE THREAD

**Issue by obbardc** [rauc/rauc#545]
Currently casync bundles are built with the default casync chunk parameters, which currently is to build chunks with an average size of 64K.

This leaves us with lots of small chunks, when downloading over http with a lot rtt this can cause long delays.

Do you think this is worth passing this option through to casync?

**Comment by ejoerns** [comment]
IMHO there is nothing that speaks against adding a configuration option for this.

**Comment by obbardc** [comment]
ack, will try to put it on my backlog ;-)

**Comment by jluebbe** [comment]
You can take a look at https://github.com/rauc/rauc/pull/537 for how this was done for mksquashfs.

**Comment by ejoerns** [comment]
This raises the question if this is common enough to add a distinct configuration option, such as `chunk-size` or if this should also go into something like `casync-args`.

**Comment by jluebbe** [comment]
> This raises the question if this is common enough to add a distinct configuration option, such as `chunk-size` or if this should also go into something like `casync-args`.

I'd prefer a `--casync-args` option, instead of passing them through separately. It won't be long until someone wants to try different compression options. ;)

**Comment by ejoerns** [comment]
That `--casync-args` would anyway be required is clear. But we should provide distinct options for the common configuration parameters, like we have for `storepath` and `tmppath`. But, maybe the generic one is sufficient for this case first of all.

**Comment by EugenWiens** [comment]
I think that the chunk size is a generic problem. This parameter would help
to setup better OTA updates regarding the bandwidth.

Enrico Jorns <notifications@github.com> schrieb am Fr., 28. Feb. 2020,
16:07:

**Comment by obbardc** [comment]
Personally I think it would be best to add `--casync-args` personally for potential future casync changes.
