### ISSUE TITLE
How to cross compile casync

### ISSUE THREAD

**Issue by ufechner7** [rauc/rauc#657]
I guess some of you did already cross compile casync for arm. An hints how to do that with buildroot?
I already compiled git master on the host (Ubuntu 18.04), but now I need the target version.

**Comment by ejoerns** [comment]
Maybe the PTXdist recipe is something one could use as a blueprint?
https://git.pengutronix.de/cgit/ptxdist/tree/rules/casync.make

**Comment by ufechner7** [comment]
Looks not too complicated! Buildroot does support meson based packages: http://nightly.buildroot.org/#_infrastructure_for_meson_based_packages

Thanks for the quick response!
