### ISSUE TITLE
`invalid slot status 0` when using custom bootloader

### ISSUE THREAD

**Issue by om26er** [rauc/rauc#660]
We are trying to enable RAUC with CBoot(Nvidia Bootloader), initally we are looking to get this thing working following https://rauc.readthedocs.io/en/latest/integration.html#custom, at a later stage we do plan to support the implementation in C i.e. upstreaming a RAUC backend for CBoot.

So I wrote a simple shell script to test things, but it says "invalid slot satus 0", not sure what's causing that. Below is a naive script

```
#!/bin/sh

arg1=$1
arg2=$2

echo $@ >> file1

if [ "$arg1" = "get-primary" ]
then
        echo "APP_b"
        exit 0
fi

if [ "$arg1" = "get-state" ]
then
        echo "good"
        exit 0
fi
```

**Comment by om26er** [comment]
system.cfg looks like
```
[system]
compatible=Dev
bootloader=custom

[keyring]
path=/etc/rauc/ca.cert.pem
 
[slot.rootfs.0]
device=/dev/mmcblk0p1
type=ext4
bootname=APP

[slot.rootfs.1]
device=/dev/mmcblk0p2
type=ext4
bootname=APP_b

[handlers]
bootloader-custom-backend=cboot-script
```

**Comment by om26er** [comment]
Ok, I think I might have found the root of the issue here. RAUC looks in the `/proc/cmdline` to detect the currently active slot. In case of Xavier NX, there is nothing that RAUC recognizes

```
root@jetson-xavier-nx-devkit:~# cat /proc/cmdline 
console=ttyTCU0,115200 console=ttyTCU0,115200 console=tty0 fbcon=map:0 video=tegrafb no_console_suspend=1 earlycon=tegra_comb_uart,mmio32,0x0c168000 gpt tegra_fbmem=0x800000@0xa069c000 lut_mem=0x2008@0xa0696000 usbcore.old_scheme_first=1 tegraid=19.1.2.0.0 maxcpus=6 boot.slot_suffix=_b boot.ratchetvalues=0.4.2 vpr_resize sdhci_tegra.en_boot_part_access=1
```

So I think we'd need to change RAUC to "understand" the `boot.slot_suffix=_b` parameter in the cmdline on the Nvidia Jetson platform.

**Comment by om26er** [comment]
This part of the docs also mentions that https://rauc.readthedocs.io/en/latest/integration.html#booted-slot-detection

So I hacked RAUC to set a hard-coded `root=` parameter using the below patch
```
diff --git a/src/context.c b/src/context.c
index 968266b..3f69bab 100644
--- a/src/context.c
+++ b/src/context.c
@@ -276,7 +276,9 @@ static void r_context_configure(void)
                g_warning("Ignoring surrounding whitespace in system variant: %s", context->config->system_variant);
 
        if (context->bootslot == NULL) {
-               context->bootslot = g_strdup(get_cmdline_bootname());
+               context->bootslot = "root=/dev/mmcblk0p2";
+               //context->bootslot = "rauc.slot=APP_b";
+               //context->bootslot = g_strdup(get_cmdline_bootname());
        }
 
        if (context->mountprefix) {
```
Now RAUC is able to print the "status"
```
root@jetson-xavier-nx-devkit:~# rauc status
=== System Info ===
Compatible:  RaspberryPi4
Variant:     
Booted from: (null) (root=/dev/mmcblk0p2)

=== Bootloader ===
Activated: rootfs.1 (APP_b)

=== Slot States ===
x [rootfs.1] (/dev/mmcblk0p2, ext4, inactive)
        bootname: APP_b
        mounted: /
        boot status: good

o [rootfs.0] (/dev/mmcblk0p1, ext4, inactive)
        bootname: APP
        boot status: good
```
However it shows both slots as "inactive" and when I try to mark a specific slot as active, it prints below message
```
root@jetson-xavier-nx-devkit:~# rauc status mark-active APP_b
rauc-Message: 22:17:10.040: rauc status: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code30: Failed to determine slot states: Did not find booted slot
```

**Comment by ejoerns** [comment]
@om26er to get what you attempt to do, it should be

``` diff
-context->bootslot = "root=/dev/mmcblk0p2";
+context->bootslot = "/dev/mmcblk0p2";
```

You can see in this line:

> Booted from: (null) (root=/dev/mmcblk0p2)

that it does not detect the booted slot correctly

**Comment by ejoerns** [comment]
The generic way of forwarding the bootname from the bootloader to rauc is to use `rauc.slot=<name>`.
The boot selection script in the bootloader should add this command line parameter. I assume this is not possible in your case, as you do not script anything but only rely on the provided mechinsm, right?

**Comment by om26er** [comment]
Thanks a lot 

> @om26er to get what you attempt to do, it should be
> 
> ```diff
> -context->bootslot = "root=/dev/mmcblk0p2";
> +context->bootslot = "/dev/mmcblk0p2";
> ```
> 
> You can see in this line:
> 
> > Booted from: (null) (root=/dev/mmcblk0p2)
> 
> that it does not detect the booted slot correctly

Great, that worked

**Comment by om26er** [comment]
> I assume this is not possible in your case, as you do not script anything but only rely on the provided mechinsm, right?

yeah, that is correct, I am not sure if Nvidia provides the tools to update the kernel cmdline from the userspace, if there was a way to do that then I guess there won't be a need to patch RAUC.

**Comment by oberstet** [comment]
> I am not sure if Nvidia provides the tools to update the kernel cmdline from the userspace, if there was a way to do that then I guess there won't be a need to patch RAUC.

does that help? not sure ..

https://forums.developer.nvidia.com/t/update-kernel-command-line-using-flash-sh-script-solved/65893/4

**Comment by om26er** [comment]
@oberstet it seems `flash.sh` is used to actually flash an image, in the above link it involves rewriting partition. It seems for OE4T project, they don't enable `extlinux` (official way to update cmdline from a booted system(https://forums.developer.nvidia.com/t/set-kernel-commandline-from-userspace/160242)) due to it being buggy in the Xavier platform https://github.com/OE4T/meta-tegra/issues/502.

So I ended up writing this patch for RAUC, which fixes the issue for us.
```
ubuntu@ip-172-31-39-46:~/rauc$ git diff
diff --git a/src/context.c b/src/context.c
index 20ccecd..e66e5af 100644
--- a/src/context.c
+++ b/src/context.c
@@ -29,6 +29,7 @@ static const gchar* get_cmdline_bootname(void)
        g_autofree gchar *contents = NULL;
        g_autofree gchar *realdev = NULL;
        const char *bootname = NULL;
+       const char *suffix = NULL;
 
        if (context->mock.proc_cmdline)
                contents = g_strdup(context->mock.proc_cmdline);
@@ -52,6 +53,16 @@ static const gchar* get_cmdline_bootname(void)
                        return bootname;
        }
 
+       suffix = regex_match("boot\\.slot_suffix=(\\s+)", contents);
+       if (g_strcmp0(suffix, " ") == 0) {
+               return "APP";
+       }
+
+       suffix = regex_match("boot\\.slot_suffix=(\\S+)", contents);
+       if (g_strcmp0(suffix, "_b") == 0) {
+               return "APP_b";
+       }
+
        bootname = regex_match("root=(\\S+)", contents);
        if (!bootname)
                return NULL;
```

**Comment by oberstet** [comment]
alright! not sure I get all the details;) but it seems "some patch is required somewhere" .. and if that "somewhere" can be RAUC to make it work for us, I'd be fine adding the patch to our Yocto layer / build. Of course, best would be upstreaming ..

**Comment by oberstet** [comment]
> on a sidenote: of course "best" would be if Nvidia just used uboot. why do I have to (practically) use this cboot stuff anyways? I don't want their bugs. sure .. Nvidia;) whatever.

**Comment by ejoerns** [comment]
Yes, I am also not sure if we should encourage using custom close-sourced bootloaders.. ;) But we should encourage and enable using RAUC, thus its a dilemma ;)

@om26er So the `boot.slot_suffix` is simply empty when the primary copy is used?

If it was just `"_a"` then a generic solution with just a customizable match that allows setting `bootname` would work. But yes 'empty string' would be a bad boot name to handle.

**Comment by oberstet** [comment]
> Yes, I am also not sure if we should encourage using custom close-sourced bootloaders.. ;) But we should encourage and enable using RAUC, thus its a dilemma ;)

yeah, true. I would argue: _encourage_ pure open-source solutions (when available), but (also) _support_ closed-source (when those are common / just the ground truth). this automatically nudges users to OSS, but supports the widest range of users and puts the ultimate control in user hands. (user == app/distro developer)

in this specific case: I _have_ to use closed source cboot on nvidia HW (one cannot use uboot? it wouldn't be "supported" by nvidia? which cam be a problem in a commercial context) - and I _want_ to use RAUC;)

**Comment by om26er** [comment]
> So the `boot.slot_suffix` is simply empty when the primary copy is used?

Yes, it's empty when A partition is selected and '_b' for B. (see https://github.com/OE4T/meta-tegra/issues/502#issuecomment-733077504)

Also while CBoot is Nvidia specific, it is open-source software and meta-tegra builds it from source. It downloadable here https://developer.nvidia.com/embedded/downloads or the direct link https://developer.nvidia.com/cboot-sources-jetson-agx-xavier-and-jetson-xavier-nx-32.4.4

**Comment by oberstet** [comment]
> CBoot is Nvidia specific, it is open-source software

CBoot is most certainly _not_ OSS (at least by OSI definition).

* It is licensed under the "NVIDIA Jetson CPU Bootloader License" ... which is shite. I just took the effort to download and look into.
* It is distributed as a tarball of sources. Where is the source repo with full history? Where is the issue tracker? Where do I file my PR?

Actually, my real question is: how can I get rid of this Nvidia crap as much as possible and practically?

For the boot loader, that question boils down to: could be use Uboot in the Jetson NX?

However, then I actually don't care that much. I personally won't use Nvidia anyways. It is "enforced upon" me .. we should do that (because ..), but _also_ do the right thing: support a non-Nvidia open device as well (NXP i.MX8M). Btw: the Broadcom SoC just sucks a bit less .. but still. Who is using the GPU to boot a SoC? crap;)

**Comment by oberstet** [comment]
eg these cboot license terms are specifically interesting:

```
3.3 Use Limitation. The Work and any derivative works thereof may only be used
with systems that include NVIDIA Jetson hardware.

3.4 Patent Claims. If you bring or threaten to bring a patent claim against any
Licensor (including any claim, cross-claim or counterclaim in a lawsuit) to
enforce any patents that you allege are infringed by any Work, then your rights
under this License from such Licensor (including the grant in Section 2.1) will
terminate immediately.

3.6 Termination. If you violate any term of this License, then your rights
under this License (including the grant in Section 2.1) will terminate
immediately.
```

my completely uninformed, layman reading of this:

cboot can only be used with Nvidia hardware. if you sue Nvidia for _anything_ patents (possibly completely unrelated to cboot), then your _cboot_ license terminates immediately (and hence all products that include cboot are immediately infringing). same for any violation in general.

**Comment by om26er** [comment]
Nvidia is getting rid of CBoot in 2022 and will be using UEFI. I am closing this issue for now as we have this thing working with a simple patch to RAUC
