### ISSUE TITLE
Taking ownership of bundle file fails when file is placed on read-only mounted filesystem

### ISSUE THREAD

**Issue by mhei** [rauc/rauc#678]
One usage scenario in our product is that the bundle can be placed on a USB pen drive which is mounted read-only. I tested rauc v1.5 and the update fails with the following message:
`failed to take ownership of bundle: failed to chmod bundle: Read-only file system`
Maybe this should be handled as special case?

**Comment by jluebbe** [comment]
This was explicitly rejected as rauc cannot detect reliably it is mounted RW somewhere else or later at runtime.
 
Is the file owner or permissions the problem in your case? If it's only the permissions, you could use fmask=0022 as a mount option.

**Comment by mhei** [comment]
Yes, I got it. And yes, our vfat mount options were complete stupid, but I've to blame myself... Sorry for the noise.
