### ISSUE TITLE
Does Rauc support Grub2 or trustedgrub?

### ISSUE THREAD

**Issue by niharikamurthy** [rauc/rauc#682]
Does Rauc support Grub2 or trustedgrub?

**Comment by ejoerns** [comment]
Yes: https://rauc.readthedocs.io/en/latest/integration.html#grub

trustedgrub probably, as it is basically an extended grub. But untested.

**Comment by ejoerns** [comment]
@niharikamurthy Did that answer your question sufficiently? If yes, feel free to close, otherwise, feel free to ask.
