### ISSUE TITLE
rauc install fails with dosfstools v4.2

### ISSUE THREAD

**Issue by bertouttier** [rauc/rauc#718]
When using rauc install on a system with dosfstools v4.2 installed, the installation fails (with dosfstools v4.1, everything works fine). This is because dosfstools v4.2 checks the vfat partition label name, and raises an error when it contains a '.' character. Since RAUC sets dots in vfat partition labels, the installation fails.

A workaround is to patch dosfstools in src/common.c and to allow dots in the label of the partition:
```
--- a/src/common.c
+++ b/src/common.c
@@ -350,7 +350,6 @@
             ret |= 0x02;
         if (doslabel[i] == 0x22 ||
             (doslabel[i] >= 0x2A && doslabel[i] <= 0x2C) ||
-            doslabel[i] == 0x2E ||
             doslabel[i] == 0x2F ||
             (doslabel[i] >= 0x3A && doslabel[i] <= 0x3F) ||
             (doslabel[i] >= 0x5B && doslabel[i] <= 0x5D) ||
```

What are your thoughts on fixing this?

**Comment by jluebbe** [comment]
We use the slot name as the label by default, which contains a `.`. Is there a specific reason why `.` is no longer allowed?

**Comment by ejoerns** [comment]
This was explicitly introduced with https://github.com/dosfstools/dosfstools/commit/40da1b2c0129124f70fc0ec74363c699a3a479f8, stating this is not allowed by FAT specification.

**Comment by jluebbe** [comment]
So we could replace the `.` with `~`, `-` or `_`? Any preference?

**Comment by bertouttier** [comment]
I guess `_` will do!

**Comment by ejoerns** [comment]
The original document [[1]](http://download.microsoft.com/download/0/8/4/084c452b-b772-4fe5-89bb-a0cbf082286a/fatgen103.doc) says

> The following characters are not legal in any bytes of DIR_Name: 
    • Values less than 0x20 except for the special case of 0x05 in DIR_Name[0] described above.
    • 0x22, 0x2A, 0x2B, 0x2C, 0x2E, 0x2F, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F, 0x5B, 0x5C, 0x5D, and 0x7C. 
> 
> Here are some examples of how a user-entered name maps into DIR_Name:
> 
> “foo.bar”            -> “FOO     BAR”
> “FOO.BAR”            -> “FOO     BAR”
> “Foo.Bar”            -> “FOO     BAR”
> “foo”                -> “FOO        “
> “foo.”               -> “FOO        “
> “PICKLE.A”           -> “PICKLE  A  “
> “prettybg.big”       -> “PRETTYBGBIG”
> “.big”               -> illegal, DIR_Name[0] cannot be 0x20


Anyway, not sure in how DIR_Name[0] and the volume label are equal.

Using "_" sounds safe, anyway.

**Comment by Bastian-Krause** [comment]
> Anyway, not sure in how DIR_Name[0] and the volume label are equal.

The volume name (label) is actually stored as the name of a file with the ATTR_VOLUME_ID attribute:

> ATTR_VOLUME_ID 	There should only be one “file” on the volume that has this attribute set, and that file must be in the root directory. This name of this file is actually the label for the volume.

 [[1]](http://download.microsoft.com/download/0/8/4/084c452b-b772-4fe5-89bb-a0cbf082286a/fatgen103.doc)

**Comment by ejoerns** [comment]
@Bastian-Krause Ok, missed the part that these rules are valid for each FAT entry (and thus also for the 'volume file'). Thx!
