### ISSUE TITLE
Install dependencies on README slightly wrong

### ISSUE THREAD

**Issue by hongkongkiwi** [rauc/rauc#733]
Hi,

Looks like the install instructions are missing these:
`libjson-glib-dev libcurl4-openssl-dev libssl-dev`

Please update dependencies for installation to show:
`sudo apt-get install build-essential automake libtool libdbus-1-dev libglib2.0-dev libjson-glib-dev libcurl4-openssl-dev libssl-dev`

**Comment by ejoerns** [comment]
@hongkongkiwi which instructions are you referring to? 

The README.rst lists these as far as I can see: https://github.com/rauc/rauc#host-build-prerequisites (with the virtual libcurl3-dev instead)

**Comment by hongkongkiwi** [comment]
I'm sorry, I must have misread, yes I just tested again, totally correct.
