### ISSUE TITLE
mtd-utils 2.1.3 breaks mtdram-based tests of NOR handlers

### ISSUE THREAD

**Issue by ejoerns** [rauc/rauc#788]
The test aborts with 

```
rauc:ERROR:test/update_handler.c:361:test_update_handler: assertion failed (ierror == NULL): failed to run flash_erase: Child process exited with code 255 (g-spawn-exit-error-quark, 255)
```

as calling flash_erase on the mtdram device fails.

Reproducible with:
```
$ ./qemu-test shell
[...]
# flash_erase /dev/mtd0 0 0
Erasing 32768 Kibyte @ 0 --  0 % complete libmtd: error!: bad eraseblock number 255, mtd0 has 1 eraseblocks
flash_erase: error!: /dev/mtd0: MTD Erase entire chip failureTrying one by one each sector.
             error 22 (Invalid argument)
Erasing 128 Kibyte @ 0 --  0 % complete libmtd: error!: bad eraseblock number 1, mtd0 has 1 eraseblocks
flash_erase: error!: /dev/mtd0: MTD get bad block failed
             error 22 (Invalid argument)
```

When `flash_erase` doe not try to auto-detect erase block count, no failure is triggered:

```
# flash_erase /dev/mtd0 0 1
Erasing 128 Kibyte @ 0 -- 100 % complete
```

Apparently, the amount of eraseblocks looks suspicious:

```
# mtdinfo /dev/mtd0
mtd0
Name:                           mtdram test device
Type:                           ram
Eraseblock size:                131072 bytes, 128.0 KiB
Amount of eraseblocks:          1 (33554432 bytes, 32.0 MiB)
Minimum input/output unit size: 1 byte
Sub-page size:                  1 byte
Character device major/minor:   90:0
Bad blocks are allowed:         false
Device is writable:             true
```

but should be valid if 'MTD_NO_ERASE` is set and if I get http://git.infradead.org/mtd-utils.git/commit/54d68799b73e755923def1306b4da607ad45bd60 right.

But as this worked beforre, something must have changed or became pickier?
(Note: I assume I've changed from mtd-utils 2.1.2 to 2.1.3 recently).

```
# flash_erase --version
flash_erase (mtd-utils) 2.1.3
```

**Comment by jluebbe** [comment]
With mtd-utils 2.1.2, this still works:
```
# mtdinfo /dev/mtd0
mtd0
Name:                           mtdram test device
Type:                           ram
Eraseblock size:                131072 bytes, 128.0 KiB
Amount of eraseblocks:          256 (33554432 bytes, 32.0 MiB)
Minimum input/output unit size: 1 byte
Sub-page size:                  1 byte
Character device major/minor:   90:0
Bad blocks are allowed:         false
Device is writable:             true
# flash_erase /dev/mtd0 0 0
Erasing 128 Kibyte @ 1fe0000 -- 100 % complete
#
```

**Comment by jluebbe** [comment]
We should fix this in time to be included in Debian bookworm.

**Comment by ejoerns** [comment]
We consider this a bug in mtd-utils, introduced by http://git.infradead.org/mtd-utils.git/commit/54d68799b73e755923def1306b4da607ad45bd60 which not only prevents division by zero but also cases where a calculation would have been possible.

**Comment by ejoerns** [comment]
FTR: I've submitted a patch for mtd-utils to linux-mtd: http://lists.infradead.org/pipermail/linux-mtd/2022-August/094762.html

**Comment by ejoerns** [comment]
FTR: The patch has been merged into mtd-utils master: http://git.infradead.org/mtd-utils.git/commit/b83c64f7a12538417649accc1269c22d5ff074bb

**Comment by ejoerns** [comment]
FTR: The patch made it into the v2.1.5 release of `mtd-utils`.

v2.1.5 made it into Debian [bookworm](https://packages.debian.org/bookworm/mtd-utils)

I think the aim of this issue was achieved with this and it can be closed.
