### ISSUE TITLE
'tests' workflow's 'build' Job fails in 'make distcheck'

### ISSUE THREAD

**Issue by ejoerns** [rauc/rauc#790]
Currently, all workflow runs of newly submitted PRs fail with:

```
ERROR: test/install.test - Bail out! rauc:ERROR:../../test/install.c:980:install_test_bundle: assertion failed (ierror == NULL): Installation error: Error while writing status file: failed to mount slot: failed to run mount: Child process exited with code 32 (g-spawn-exit-error-quark, 32)
PASS: test/rauc.t 1 - rauc noargs
PASS: test/rauc.t 2 - rauc invalid arg
[....]
PASS: test/update_handler.test 41 /update_handler/update_handler/ext4_to_ext4/no-image
PASS: test/update_handler.test 42 /update_handler/update_handler/ext4_to_ext4/no-slot
ERROR: test/update_handler.test - Bail out! rauc:ERROR:../../test/update_handler.c:375:test_update_handler: assertion failed: (test_mount(slotpath, mountprefix))
```

See for example: https://github.com/rauc/rauc/runs/3990696249?check_suite_focus=true

**Comment by ejoerns** [comment]
Meanwhile, action runner upgraded to

    Linux f1d5803af3c8 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021 x86_64 GNU/Linux

However, problem persists.

It is also unrelated to `make distcheck` (as above findings already suggested) but seems to be triggered only there during test suite runs. In a more condensed minimal example it can also be reproduced with a normal `make check`.

Thus deactivating distcheck might really only be a very temporary hack.

**Comment by ejoerns** [comment]
Having the loop mount still present after `unmount` can be reproduced quite easily:

    # create target device
    dd if=/dev/zero of=$TMPDIR/target-dev bs=1M count=10
    /sbin/mkfs.ext4 -F -I 256 $TMPDIR/target-dev > /dev/null

    mkdir $TMPDIR/mount
    mount -t ext4 -v $TMPDIR/target-dev $TMPDIR/mount
    umount -d -v $TMPDIR/mount
    losetup -d $TMPDIR/target-dev || true
    losetup -j $TMPDIR/target-dev

While, in all cases, `losetup -d` fails with:

    /tmp/tmp.LYY3Xj82XZ/target-dev: failed to use device: No such device

a later `losetup -j` still sometimes shows

    /dev/loop0: [0055]:3200305 (/tmp/tmp.LYY3Xj82XZ/target-dev)

This seems to be more or less intentional as the kernel explicitly performs a lazy loop device destruction since
https://github.com/torvalds/linux/commit/a1ecac3b0656a68259927c234e505804d33a7b83

Thus we cannot be sure that the device is not in use anymore after umount.

In the actual failure case in the tests, we can also verify with `losetup -j <path/to/slot-device>` that the loop device is still associated. Even after having written data to it (which should take a bit of time at least).

Then RAUC attempts to mount the slot device again (for writing status file) and the loop device logic apparently (see logs in previous comments) re-uses the existing loop device, probably unaware that the underlying device has changed in the meantime  (as it was updated!).

Opening the slot device with `O_EXCL` for writing (as the default handler already does) does not seem to help here as the device is not a real block device (but a file) and man 2 open says:

    In general, the behavior of O_EXCL is undefined if it is used without O_CREAT.  There is one exception: on Linux 2.6 and later, O_EXCL can be used without O_CREAT if path‐
    name refers to a block device.  If the block device is in use by the system (e.g., mounted), open() fails with the error EBUSY.

**Comment by ejoerns** [comment]
**Reproduced it outside of RAUC**:

https://github.com/ejoerns/rauc/runs/4305119847?check_suite_focus=true

With

https://github.com/ejoerns/rauc/blob/23f298f85b4c5e37a7eff257e5c5bd3c8e87c9dd/test/test.sh

Not sure why, but seems to be related to the increased number of additional loop mounts (compared to previous unsuccessful attempts of reproducing it).

**Comment by ejoerns** [comment]
Also fails:

* on ubuntu-18.04 runner (with kernel 5.4.0-1063-azure # 66 ~18.04.1-Ubuntu)
* in debian:testing docker container (with util-linux 2.37, etc.)

Does NOT fail:

* on local debian-testing in various Debian kernel versions down to v5.8.0
* on ubuntu 20.04 server with ubuntu kernel 5.4.0-65-generic

Interesting is, that when adding more loop devs, I can reproduce the still-available loopdev association locally, but do not see the ext4 mount issue.

Another difference I still see are the capacity change logs in kernel that I do not get in any other constellation than on the github runner. They happen on each successful mount as well as on the unsuccessful.

Final failure dmesg log ist still:
```
[   94.320238] loop9: detected capacity change from 0 to 102400
[   94.338585] EXT4-fs (loop9): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[   94.686178] EXT4-fs error (device loop9): ext4_get_journal_inode:5257: inode #8: comm mount: iget: checksum invalid
[   94.697038] EXT4-fs (loop9): no journal found
```

So this might really turn out to be a runner-specific **caching** problem!?

This is underlined by tests that show that a

    sleep 0.5

does not fix the failure while a

    time echo 1 > /proc/sys/vm/drop_caches

seems to 'fix' it.

**Comment by ejoerns** [comment]
I've dumped a minimal example with comparing sleep and cache drop here:

https://github.com/ejoerns/loopfail

Log: https://github.com/ejoerns/loopfail/runs/4312255276?check_suite_focus=true

**Comment by a3f** [comment]
> Note: While some prior assumptions pointed towards the loop_set_block_size: loop5 () has still dirty pages (nrpages=2) error message, I could not find this in the last log.

FWIW, see #928 for some info about the warning. It's probably unrelated to the issue here.

**Comment by ejoerns** [comment]
Currently, I do neither see how we can further debug this nor this issue has hit us during the last tests.
Thus we can close this first of all and probably reopen it in case of new findings
