### ISSUE TITLE
Does RAUC automatically adjust BOOT_ORDER?

### ISSUE THREAD

**Issue by hongkongkiwi** [rauc/rauc#793]
In our system using uboot, we have:
* system0
* system1
* rescue
* recovery

Will RAUC automatically update the BOOT_ORDER when doing an update? In which script can I handle this process myself? (do I need to?)

The reason I'm asking this is because when we update system1, I would like the order to always keep "rescue" and "recovery" as the last slots.

e.g. after updating system1 BOOT_ORDER should look like "system1 system0 rescue recovery".

after updating system0 BOOT_ORDER should look like "system0 system1 rescue recovery".

after updating recovery or rescue I still want them to appear last because we don't necessarily want to boot these upon next boot.

**Comment by jluebbe** [comment]
Slots without a bootname don't trigger the bootloader communication.

Please reopen if this is still an issue for your use-case.
