### ISSUE TITLE
keyring as archive file in test dir?

### ISSUE THREAD

**Issue by hongkongkiwi** [rauc/rauc#799]
In the test directory the manifest file has this line

```
[keyring]
archive=release.tar
```

I couldn't find any mention of keyring pointing to an archive in docs, is this a new or obsolete feature?

**Comment by ejoerns** [comment]
Good catch! Seems as if I missed these in #723. This is a remnant from the long deprecated 'network' (non-bundle) mode.

Would you like to make a PR for removing it (finally)?
