### ISSUE TITLE
rauc install fails with busybox tar: invalid tar magic

### ISSUE THREAD

**Issue by gavinschenk** [rauc/rauc#85]
Hi,

I had problems getting rauc work with busybox tar. Using nativ tar rauc just works fine!
Maybe not a bug but worth to mention it in documentation?

with default busybox tar settings
Dec 02 09:36:57 CI4000 rauc[1094]: tar: invalid tar magic

with all tar busybox  options enabled
Dec 02 09:50:16 CI4000 rauc[1094]: tar: unknown typeflag: 0x56

Regards
Gavin

**Comment by ejoerns** [comment]
You have to enable `FEATURE_TAR_AUTODETECT` for busybox tar as it has to be able to detect the compression method used for compressing the tar.

This we should mention in the documentation, yes.

Regards, Enrico

**Comment by gavinschenk** [comment]
A colleague tested it with FEATURE_TAR_AUTODETECT and it works, thanks!

**Comment by ejoerns** [comment]
PR #95 got merged which extends documentation to mention that the tar auto detection feature has to be enabled when using Busybox tar.
Do you think this will be sufficient to better guide new users of RAUC?
