### ISSUE TITLE
Prerequisites @ README

### ISSUE THREAD

**Issue by atar-axis** [rauc/rauc#904]
Is it neccessary for the kernel parameters to be "=y" instead of "=m"?
On a common ubuntu system there are some parameters, like `_DM_VERITY`,  `_DEV_NBD` and `_DM_CRYPT` which are just modules instead of builtins. Is that a problem?

**Comment by jluebbe** [comment]
They just need to be enabled, either `=y` or `=m` should be fine as long your module loading is working correctly.
