### ISSUE TITLE
Installling verity bundle fails

### ISSUE THREAD

**Issue by AlfTeleco** [rauc/rauc#922]
Hello everyone, 

Rauc is a wonderful tool that I've been working with since a couple of months, but once in a while it comes out with some problems. 
I am trying to move on to the verity bundle format. I've been able to create bundles with this format and the command "rauc info verity_bundle.raucb" gives a good looking output. 
Nonetheless when I try to install the bundle process frezees in right after the step " 60% Checking manifest contents done.". You can see the prompt here: 

~~~sh

root@root:/home/debian# rauc install --debug update_device_verity_vol.raucb 
rauc-Message: 11:16:26.828: Debug log domains: 'rauc'
(rauc:379): rauc-DEBUG: 11:16:26.841: install started
(rauc:379): rauc-DEBUG: 11:16:26.842: input bundle: /home/debian/update_device_verity_vol.raucb
   string "type='signal',sender='de.pengutronix.rauc',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/',arg0='de.pengutronix.rauc.Installer'"
   string "type='signal',sender='de.pengutronix.rauc',interface='de.pengutronix.rauc.Installer',path='/'"
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='de.pengutronix.rauc'"
   string "de.pengutronix.rauc"
   string "de.pengutronix.rauc"
   string "de.pengutronix.rauc.Installer"
(rauc:379): rauc-DEBUG: 11:16:26.895: Trying to contact rauc service
method call time=1655378186.906671 sender=:1.15 -> destination=:1.12 serial=8 path=/; interface=de.pengutronix.rauc.Installer; member=InstallBundle
   string "/home/debian/update_device_verity_vol.raucb"
   string "de.pengutronix.rauc.Installer"
installing
   string "de.pengutronix.rauc.Installer"
   string "de.pengutronix.rauc.Installer"
  0% Installing
  0% Determining slot states
   string "de.pengutronix.rauc.Installer"
 20% Determining slot states done.
   string "de.pengutronix.rauc.Installer"
 20% Checking bundle
   string "de.pengutronix.rauc.Installer"
 20% Verifying signature
 40% Verifying signature done.
   string "de.pengutronix.rauc.Installer"
 40% Checking bundle done.
   string "de.pengutronix.rauc.Installer"
 40% Checking manifest contents
   string "de.pengutronix.rauc.Installer"
   string "de.pengutronix.rauc.Installer"
 60% Checking manifest contents done.
   string "dev-mapper-rauc\x2dverity\x2dbundle.device"
   object path "/org/freedesktop/systemd1/unit/dev_2dmapper_2drauc_5cx2dverity_5cx2dbundle_2edevice"

~~~

It just could stay there forever. I think it could be smth related to dbus comms or maybe /dev/loop0 handling...

Any ideas? Any answer would be much appreciated. 

Thanks in advance!

**Comment by jluebbe** [comment]
Please also attach the log output from the rauc service.

**Comment by AlfTeleco** [comment]
Hello! Thanks for the quick answer, here it is the rauc service output: 

~~~sh

root@A11926:/home/debian# stty cols 200
root@A11926:/home/debian# systemctl status rauc
�● rauc.service - Rauc Update Service
   Loaded: loaded (/lib/systemd/system/rauc.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2022-06-16 13:02:27 UTC; 15min ago
     Docs: https://rauc.readthedocs.io
 Main PID: 322 (rauc)
    Tasks: 3 (limit: 1065)
   Memory: 31.0M
   CGroup: /system.slice/rauc.service
           �└�─322 /usr/local/bin/rauc --mount=/run/rauc service

Jun 16 13:09:43 A11926 rauc[322]: installing /home/debian/update_device_plain_vol.raucb: Checking and mounting bundle...
Jun 16 13:09:43 A11926 rauc[322]: Reading bundle: /home/debian/update_device_plain_vol.raucb
Jun 16 13:09:43 A11926 rauc[322]: Verifying bundle signature... 
Jun 16 13:09:43 A11926 rauc[322]: Verified detached signature by 'C = ES, O = Owasys S.L, OU = Owasys TI, CN = Owasys_intermediate_CA'
Jun 16 13:09:43 A11926 rauc[322]: Mounting bundle '/home/debian/update_device_plain_vol.raucb' to '/run/rauc/bundle'
Jun 16 13:09:44 A11926 rauc[322]: Configured loop device '/dev/loop0' for 30281728 bytes
Jun 16 13:09:44 A11926 rauc[322]: Installation error: Destination device '/dev/ubi_MAIN_device' not found
Jun 16 13:09:44 A11926 rauc[322]: installing /home/debian/update_device_plain_vol.raucb: Installation error: Destination device '/dev/ubi_MAIN_device' not found
Jun 16 13:09:44 A11926 rauc[322]: installing /home/debian/update_device_plain_vol.raucb: finished
Jun 16 13:09:44 A11926 rauc[322]: installing `/home/debian/update_device_plain_vol.raucb` failed: 1

~~~

BR

**Comment by AlfTeleco** [comment]
Thanks for the quick answer! Here it is: 

~~~sh

oot@A11926:/home/debian# systemctl status rauc
�● rauc.service - Rauc Update Service
   Loaded: loaded (/lib/systemd/system/rauc.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2022-06-16 13:22:38 UTC; 1min 10s ago
     Docs: https://rauc.readthedocs.io
 Main PID: 324 (rauc)
    Tasks: 4 (limit: 1065)
   Memory: 1.6M
   CGroup: /system.slice/rauc.service
           �└�─324 /usr/local/bin/rauc --mount=/run/rauc service

Jun 16 13:22:38 A11926 systemd[1]: Started Rauc Update Service.
Jun 16 13:23:33 A11926 rauc[324]: input bundle: /home/debian/update_device_verity_vol.raucb
Jun 16 13:23:33 A11926 rauc[324]: Active slot bootname: MAIN
Jun 16 13:23:33 A11926 rauc[324]: installing /home/debian/update_device_verity_vol.raucb: started
Jun 16 13:23:33 A11926 rauc[324]: installing /home/debian/update_device_verity_vol.raucb: Checking and mounting bundle...
Jun 16 13:23:33 A11926 rauc[324]: Reading bundle: /home/debian/update_device_verity_vol.raucb
Jun 16 13:23:33 A11926 rauc[324]: Verifying bundle signature... 
Jun 16 13:23:33 A11926 rauc[324]: Verified inline signature by 'C = ES, O = Owasys S.L, OU = Owasys TI, CN = Owasys_intermediate_CA'
Jun 16 13:23:33 A11926 rauc[324]: Mounting bundle '/home/debian/update_device_verity_vol.raucb' to '/run/rauc/bundle'
Jun 16 13:23:33 A11926 rauc[324]: Configured loop device '/dev/loop0' for 30523392 bytes

~~~

BR

**Comment by jluebbe** [comment]
Could you change your rauc.service to run with `--debug` as well (don't forget `systemd daemon-reload`). And use journalctl to get the full output (which will be larger with debug).

You can also use gdb to get a backtrace from the rauc services' threads.

Just a guess: Did you enable the kernel options (i.e. dm-verity)? That shouldn't lead to a hang though.

**Comment by jluebbe** [comment]
Hmm, the log output seems good until it stops. Did you see anything interesting via gdb (`thread apply all bt`)? Does the rauc process have any sub-processes running at this point?

**Comment by ejoerns** [comment]
> Hello, I've tinkering with gdb from eclipse but cannot see anything special. 

Even if you do not see 'anything special', you should be at least able to see which is the call that hangs by interrupting and dumping a backtrace. Don't you?

>Is there any chance that this has smth to do with Dbus? how could I assure that dbus comms are working properly?

The hang happens between setting up the loop device and setting up the dm-verity device. There is no D-Bus involved.

**Comment by jluebbe** [comment]
If you want to simplify your setup, you could used the `--disable-service` configure switch. The single RAUC process could be simpler.

**Comment by ejoerns** [comment]
@AlfTeleco do you have any further findings on this?

Based on the information provided so far, I see no way to further encircle the cause of the issue described.

**Comment by AlfTeleco** [comment]
Hello everyone, thanks for the attention on this issue. These past days I've been quite busy but I didn't forget. I still have to test debugging rauc with the backtrace option enable. I'll come back with some traces a soon as I can do it. 
Thanks again.

**Comment by AlfTeleco** [comment]
Hello everyone, 

I'm currently attached to my system from eclipse with gdb-multiarch. I started the application and try to run the command "rauc install verity_bundle.raucb". 
Once the process gets to the point where it stalls there are 3 threads: 

1. Thread rauc
2. Thread gmain
3. Thread gdbus

After waiting for some time at "Checking manifest content done." step I Ctrl+c and try "backtrace", this is what I've got: 
~~~sh
(gdb) bt      
#0  0xb69db744 in ?? () from target:/lib/arm-linux-gnueabihf/libc.so.6
#1  0xb6a57210 in poll () from target:/lib/arm-linux-gnueabihf/libc.so.6
#2  0xb6d9fa04 in ?? () from target:/usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
~~~

The same happens when I try from every thread.

Many thanks!

**Comment by ejoerns** [comment]
> ```shell
> (gdb) bt      
> #0  0xb69db744 in ?? () from target:/lib/arm-linux-gnueabihf/libc.so.6
> #1  0xb6a57210 in poll () from target:/lib/arm-linux-gnueabihf/libc.so.6
> #2  0xb6d9fa04 in ?? () from target:/usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> ```

Do you have the option to use debug symbols? Without these, it is not possible to guess what happens here.
But RAUC does not seem to play a role here according to the stack.

> My system only uses NAND as storage. **Is it possible to use dm-verity over NAND memories?** In the [Linux kernel Manual it states](https://www.kernel.org/doc/html/latest/admin-guide/device-mapper/verity.html) " _Device-Mapper’s “verity” target provides transparent integrity checking of **block devices** using a cryptographic digest provided by the kernel crypto API. This target is read-only."_

This is irrelevant since in RAUC, dm-verity is not used directly on NAND. It is used for the squashfs image (bundle) only.

**Comment by jluebbe** [comment]
Without further information (i.e. a stack trace with debug symbols), there's not much we can do here. If you have further information, feel free to reopen.
