### ISSUE TITLE
nbd-netlink kernel support required for streaming?

### ISSUE THREAD

**Issue by hongkongkiwi** [rauc/rauc#990]
The http streaming support seems to require nbd-netlink in the kernel.

We are running a 4.X series kernel and we don't have this, so this locks the feature to quite a recent kernel (seems it was added just last year).

Is there a way we can do it without requiring a recent kernel? It's unfortunate because many embedded devices have slightly older kernels so this will prevent many users from using this feature.

**Comment by jluebbe** [comment]
The netlink interface was released with v4.12 (https://github.com/torvalds/linux/commit/e46c7287b1c27683a8e30ca825fb98e2b97f1099) five years ago. The only remaining LTS without it is v4.9, which [will likely be EOL in January 2023](https://www.kernel.org/category/releases.html).

As the netlink interface is a significant improvement over the old ioctl interface and any system in the field would have to upgrade to a kernel with nbd netlink support for security reasons anyway, we decided against supporting the ioctl interface when we added streaming support.
