### ISSUE TITLE
PGP key used for (recent) releases has expired on keyservers/github

### ISSUE THREAD

**Issue by dvzrv** [rauc/rauc#992]
Hi! I'm currently trying to package rauc for Arch Linux.

This project seems to commit to a chain of trust for its releases and provides PGP signed tarballs. Arch Linux's build system can make use of that and verify tarballs using provided signatures.

The PGP key of @jluebbe (`977843FD5C3EBF76BAD4008EA58CC53DBF05E090`) used for the signature for [1.8](https://github.com/rauc/rauc/releases/tag/v1.8) has expired in June though.

```
gpg --keyid-format long --list-key 977843FD5C3EBF76BAD4008EA58CC53DBF05E090
pub   rsa4096/A58CC53DBF05E090 2016-06-09 [C] [expired: 2022-06-04]
      977843FD5C3EBF76BAD4008EA58CC53DBF05E090
uid                 [ expired] Jan Lübbe <jlu@pengutronix.de>
```
The above public key has been retrieved from keyserver.ubuntu.com.

Unfortunately the retrievable PGP key data of the user on github seems currently unavailable:

```
curl https://github.com/jluebbe.gpg
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded BBF68F03E8F37941, A58CC53DBF05E090


=twTO
-----END PGP PUBLIC KEY BLOCK-----%
```

The updated (extended validity) PGP key is available via WKD though (`sq wkd get jlu@pengutronix.de`), so maybe the other two sources could be fixed. Thanks!

**Comment by jluebbe** [comment]
I've reuploaded my keys to github and they seem to be accessible again.

[keys.openpgp.org](https://keys.openpgp.org/about/usage) also has the current key and is also accessible via HKPS. I stopped using other key servers with the shutdown of sks-keyservers.net.

Does that solve your issue?
