### ISSUE TITLE
test/stats.test failure on i387

### ISSUE THREAD

**Issue by ukleinek** [rauc/rauc#996]
Hello,
I packaged rauc 1.8 for Debian and the test suite failed on i386:
https://buildd.debian.org/status/fetch.php?pkg=rauc&arch=i386&ver=1.8-1&stamp=1664982505&raw=0

The failing test is:
`g_assert_cmpfloat(r_stats_get_avg(stats), ==, 62.54615384615385);`

The problem is excess precision of the i387 architecture which can be seen when adding the following printf statements before the test:

    printf("%15.50a\n", r_stats_get_avg(stats));
    printf("%15.50La\n", (long double)r_stats_get_avg(stats));

This results in the following output:

    0x1.f45e85e85e85f0000000000000000000000000000000000000p+5
    0xf.a2f42f42f42f42f00000000000000000000000000000000000p+2

The latter value is the same as:

    0x1.f45e85e85e85e8500000000000000000000000000000000000p+5

So while the first line using a `double` has 53 base-2 digits in the significand (as expected as `DBL_MANT_DIG` is 53 on i386), the value casted to `long double` has a higher precision with (at least) 64 base-2 digits.

This makes the comparison in the assert statement above wrong.

I'm unsure about the right way to fix this. The obvious options are:
 - use `g_assert_cmpfloat_with_epsilon`
 - pass `-fexcess-precision=standard` to gcc
 - drop that assert

**Comment by jluebbe** [comment]
I'd prefer `g_assert_cmpfloat_with_epsilon`, as we don't care about the bit-exact value here.
